export const testNotes: INote[] = [
  {
    title: "note1",
    category: "Work",
    text: "note one body of text making this take a bit of a space",
    createdAt: new Date(),
  },
  {
    title: "note2",
    category: "Fitness",
    text: "note 2 body of text making this take a bit of a space",
    createdAt: new Date(),
  },
  {
    title: "note3",
    category: "Work",
    text: "note 3 body of text making this take a bit of a space",
    createdAt: new Date(),
  },
  {
    title: "note4",
    category: "Fitness",
    text: "note 4 body of text making this take a bit of a space",
    createdAt: new Date(),
  },
  {
    title: "note5",
    category: "Work",
    text: "note 5 body of text making this take a bit of a space",
    createdAt: new Date(),
  },
  {
    title: "note6",
    category: "Fitness",
    text: "note 6 body of text making this take a bit of a space",
    createdAt: new Date(),
  },
  {
    title: "note7",
    category: "Work",
    text: "note 7 body of text making this take a bit of a space",
    createdAt: new Date(),
  },
  {
    title: "note8",
    category: "Fitness",
    text: "note 8 body of text making this take a bit of a space",
    createdAt: new Date(),
  },
  {
    title: "note9",
    category: "Work",
    text: "note 9 body of  making this take a bit ofvmaking this take a bit ofmaking this take a bit ofmaking this take a bit of text making this take a bit of a spaceeeeeeeeeeeeeeeeeee",
    createdAt: new Date(),
  },
  {
    title: "note10",
    category: "Fitness",
    text: "note 10 body of text making this take a bit of a space",
    createdAt: new Date(),
  },

  {
    title: "note6",
    category: "Fitness",
    text: "note 6 body of text making this take a bit of a space",
    createdAt: new Date(),
  },
  {
    title: "note7",
    category: "Work",
    text: "note 7 body of text making this take a bit of a space",
    createdAt: new Date(),
  },
  {
    title: "note8",
    category: "Fitness",
    text: "note 8 body of text making this take a bit of a space",
    createdAt: new Date(),
  },
  {
    title: "note9",
    category: "Work",
    text: "note 9 body of text making this take a bit of a spaceeeeeeeeeeeeeeeeeee",
    createdAt: new Date(),
  },
  {
    title: "note10",
    category: "Fitness",
    text: "note 10 body of text making this take a bit of a space",
    createdAt: new Date(),
  },
  {
    title: "note6",
    category: "Fitness",
    text: "note 6 body of text making this take a bit of a space",
    createdAt: new Date(),
  },
  {
    title: "note7",
    category: "Work",
    text: "note 7 body of text making this take a bit of a space",
    createdAt: new Date(),
  },
  {
    title: "note8",
    category: "Fitness",
    text: "note 8 body of text making this making this take a bit ofmaking this take a bit ofmaking this take a bit ofmaking this take a bit ofmaking this take a bit ofmaking this take a bit ofmaking this take a bit ofmaking this take a bit ofmaking this take a bit ofmaking this take a bit ofmaking this take a bit of take a bit of a space",
    createdAt: new Date(),
  },
  {
    title: "note9",
    category: "Work",
    text: "note 9 body of text making this take a bit of a spaceeeeeeeeeeeeeeeeeee",
    createdAt: new Date(),
  },
  {
    title: "note10",
    category: "Fitness",
    text: "note 10 body of making this take a bit ofmaking this take a bit ofmaking this take a bit of text making this take a bit of a space",
    createdAt: new Date(),
  },
  {
    title: "note6",
    category: "Fitness",
    text: "note 6 body of text making this take a bit of a space",
    createdAt: new Date(),
  },
  {
    title: "note7",
    category: "Work",
    text: "note 7 body of making this take a bit of text making this take a bit of a space",
    createdAt: new Date(),
  },
  {
    title: "note8",
    category: "Fitness",
    text: "note 8 body of text making this take a bit of a space",
    createdAt: new Date(),
  },
  {
    title: "note9",
    category: "Work",
    text: "note 9 body of text making this take a bit of a spaceeeeeeeeeeeeeeeeeee",
    createdAt: new Date(),
  },
  {
    title: "note10",
    category: "Fitness",
    text: "note 10 body of text making this take a bit of making this take a bit ofmaking this take a bit of a space",
    createdAt: new Date(),
  },
];
